kind: pipeline
name: ci

steps:
- name: install
  image: composer
  commands:
  - composer install

- name: test
  image: php:7
  commands:
  - vendor/bin/simple-phpunit --configuration phpunit.xml.dist --coverage-text
