kind: pipeline
name: ci

steps:
- name: install
  image: jakzal/phpqa
  commands:
  - composer install

- name: test
  image: jakzal/phpqa
  commands:
  - vendor/bin/simple-phpunit --configuration phpunit.xml.dist --coverage-text
